name: Publish Package

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"
          cache: "gradle"

      - name: Setup Git
        run: |
          git config --global credential.helper store
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish release
        run: ./gradlew release
        env:
          GITHUB_TOKEN: ${{ github.token }}
