name: Pull Request

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"
          cache: "maven"

      - name: Build package
        run: ./mvnw -U -B verify clean package
        env:
          GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
